### PR TITLE
Stubbed gma.canbus

### PR DESCRIPTION
**Pull request by vjandrea**
Added gma.canbus.hardkey as a stub, needs more digging.

### CODE REVIEW

**Comment by Hobadee** [comment]
How did you find this function?  Did MA publish it somewhere?

Without more information, I think this should be a bit more flushed out before publishing it for user's to see... This looks fairly low-level and liable to blow up in user's faces if used incorrectly.  At a minimum, put a big fat warning at the top saying it's under investigation still.

**Comment by Hobadee** [comment]
Ah - answered 1 of my own questions... Found reference in the "api_test.lua" file provided by MA...

**Comment by vjandrea** [comment]
Hi Eric,
feel free to edit the commit as you prefer, that's only what I discovered
but I'm still digging because I get unconsistent results using the same
keycode.

andrea

**Comment by vjandrea** [comment]
Hi @Hobadee, I updated the stub with the warning as requested and I also managed to discover and verify successfully many codes.

**Comment by Hobadee** [comment]
I just attempted to build this and it isn't working properly.

[gma.canbus.lua.zip](https://github.com/Hobadee/grandMA2_LUA_ldoc/files/2669931/gma.canbus.lua.zip)

**Comment by Hobadee** [comment]
You were missing a set of double-dashes.  I fixed that, but now it's rendering all the keycodes as a giant block.

[gma.canbus.lua.zip](https://github.com/Hobadee/grandMA2_LUA_ldoc/files/2669939/gma.canbus.lua.zip)

**Comment by Hobadee** [comment]
I got the LDoc working.  Thanks for the work on getting all those keycodes.  Merging in now.

**Pull request merged**
